# Gin_Vue_Admin Global Configuration

# jwt configuration
jwt:
  jwt_secret: 'qmPlus'
  jwt_refresh_secret: '123'
  jwt_ttl: 10
  jwt_refresh_ttl: 604800 # 86400*7

# zap logger configuration
zap:
  level: 'info'
  format: 'json'
  prefix: ''
  director: 'storage/logs'
  link_name: 'latest_log'
  show_line: true
  encode_level: 'LowercaseColorLevelEncoder'
  stacktrace_key: 'stacktrace'
  log_in_console: true

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# email configuration
email:
  to: 'xxx@qq.com'
  port: 465
  from: 'xxx@163.com'
  host: 'smtp.163.com'
  is_ssl: true
  secret: 'xxx'
  nickname: 'test'

# casbin configuration
casbin:
  model_path: './resource/rbac_model.conf'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db_type: 'mysql'
  oss_type: 'local'
  use_multipoint: false

# captcha configuration
captcha:
  key_long: 6
  img_width: 240
  img_height: 80

# mysql connect configuration
mysql:
  host: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db_name: 'db_test'
  username: 'root'
  password: 'ma123456ma'
  max_idle_connections: 10
  max_open_connections: 10
  log_mode: false

# local configuration
local:
  path: 'uploads/file'

# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 和 域名地址)
qiniu:
  zone: 'ZoneHuadong'
  bucket: 'qm_plus_img'
  img_path: 'http://qmplusimg.henrongyi.top'
  use_https: false
  access_key: '25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ'
  secret_key: 'pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY'
  use_cdn_domains: false