# yaml 配置
version: "3.7"
services:
  demo_app:
    container_name: app_server
    build:
      context: "../"
      dockerfile: "./deploy/Dockerfile"
    ports:
      - "8888:8888"
    restart: always
    privileged: true