mysql:
  read:
    host: "127.0.0.1"
    port: "3306"
    database: "legendage_mall"
    username: "cqjs_prod"
    password: "wNem2D6$6JZmRoMj"
  write:
    host: "127.0.0.1"
    port: "3306"
    database: "legendage_mall"
    username: "cqjs_prod"
    password: "wNem2D6$6JZmRoMj"